version: '3'

services:
  nginx-rtmp:
    build:
      dockerfile: Dockerfile
    ports:
      - 1935:1935
      - 8080:80
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      #- ./certs:/opt/certs
      - ./nginx.conf:/etc/nginx/nginx.conf.template
